FROM ubuntu:18.04
MAINTAINER mikebentley15@gmail.com

# Install sudo for a local user
RUN apt-get -y update && \
    apt-get -y install sudo && \
    rm -rf /var/lib/apt/lists/*

# Create a local user with sudo priveledges
RUN groupadd sudo-nopw && \
    useradd \
      --create-home \
      --home-dir /home/ros-user \
      --shell /bin/bash \
      --user-group \
      --groups sudo,sudo-nopw \
      ros-user && \
    echo "%sudo-nopw ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/sudo-nopw-group
USER ros-user
WORKDIR /home/ros-user

# Setup UTF-8 locale and other dependencies
RUN sudo apt-get -y update && \
    sudo apt-get -y install locales && \
    sudo rm -rf /var/lib/apt/lists/* && \
    sudo locale-gen en_US.UTF-8 && \
    sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US.UTF-8' LC_ALL='en_US.UTF-8'

# Add the ROS 2 apt repository
RUN sudo apt-get -y update && \
    sudo apt-get -y install \
      curl \
      gnupg2 \
      lsb-release \
      && \
    sudo rm -rf /var/lib/apt/lists/* && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | \
      apt-key add - && \
    echo "deb http://packages.ros.org/ros2/ubuntu bionic main" \
      > /etc/apt/sources.list.d/ros2-latest.list

# Install ROS 2 Debian packages
RUN sudo apt-get -y update && \
    sudo apt-get -y install ros-eloquent-desktop && \
    sudo rm -rf /var/lib/apt/lists/*

# Install argcomplete
RUN sudo apt-get -y update && \
    sudo apt-get -y install python3-argcomplete && \
    sudo rm -rf /var/lib/apt/lists/*

# Install ament
RUN sudo apt-get -y update && \
    sudo apt-get -y install ros-eloquent-ament-* && \
    sudo rm -rf /var/lib/apt/lists/*

##  # Initialize rosdep
##  RUN apt-get -y update && \
##      apt-get -y install \
##        python-rosdep \
##        && \
##      rm -rf /var/lib/apt/lists/* && \
##      rosdep init
##  
##  # Install missing dependencies
##  RUN apt-get -y update && \
##      cd /opt/ros2-linux && \
##      rosdep update && \
##      rosdep install \
##        --from-paths /opt/ros2-linux/share \
##        --ignore-src \
##        --rosdistro eloquent \
##        -y \
##        --skip-keys "console_bridge fastcdr fastrtps libopensplice67 libopensplice69 osrf_testing_tools_cpp poco_vendor rmw_connext_cpp rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp rti-connext-dds-5.3.1 tinyxml_vendor tinyxml2_vendor urdfdom urdfdom_headers" && \
##      rm -rf /var/lib/apt/lists/*
##  
##  # Setup bash environment
##  RUN echo 'if [ -f "/opt/ros2-linux/setup.bash" ]; then' >> /etc/bash.bashrc && \
##      echo '  source "/opt/ros2-linux/setup.bash"'        >> /etc/bash.bashrc && \
##      echo 'fi'                                           >> /etc/bash.bashrc
##  
##  # Extra things to get it working and remove spurrious warnings
##  RUN echo "export NO_AT_BRIDGE=1" >> /etc/bash.bashrc && \
##      sed -i \
##        -e '2 a if ! [ -d "$_BUILDTIME_NDDSHOME" ] && ! [ -d "$NDDSHOME" ]; then return; fi' \
##        /opt/ros2-linux/share/connext_cmake_module/environment/connext.sh
##  
##  # Have some way to know what kind of docker container we're in
##  RUN echo "ros2" > /etc/docker-name
